In [1]:
import json

def json_reader(fname):
    """
        Read multiple json files
        Args:
            fname: str: input file
        Returns:
            generator: iterator over documents 
    """
    for line in open(fname, mode="r"):
        data = json.loads(line)
        yield {'rating': data['stars'], 'review': data['text']}
        

In [5]:
trainset = './dataset/NB/test.json'
data = json_reader(trainset)

In [6]:
import sys
import json
import time
import pickle
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression

In [ ]:
ratings = []
reviews = []

for datum in data:
    ratings.append(datum['rating'])
    reviews.append(datum['review'])

ratings = np.array(ratings)
reviews = np.array(reviews)
print (len(ratings))

In [9]:
tick = time.time()
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(reviews)
print ("Time Taken: ", time.time() - tick)

Time Taken:  18.569052934646606


In [12]:
print (X.shape)
print (type(X))

(133718, 93529)
<class 'scipy.sparse.csr.csr_matrix'>


In [27]:
classMatrices = []
for c in range(1, 6):
    classMatrices.append(np.array(ratings == c))
    print (classMatrices[c-1].shape)
    
# classMatrices = np.array(classMatrices)
print (classMatrices)

(133718,)
(133718,)
(133718,)
(133718,)
(133718,)
[array([False, False, False, ...,  True, False,  True]), array([False, False, False, ..., False, False, False]), array([False, False, False, ..., False, False, False]), array([False,  True,  True, ..., False,  True, False]), array([ True, False, False, ..., False, False, False])]


In [43]:
# print (X.shape, (np.transpose(classMatrices[0])).shape)
# Find model paramenters
PhiY = []
for c in range (0, 5):
    PhiY.append(np.sum(classMatrices[c]))
    
print (PhiY)
print (np.sum(PhiY))

[20169, 10838, 14531, 29358, 58822]
133718


In [47]:
PhiKY = []
Xt = X.transpose()

for c in range (0, 5):
    PhiKY.append( Xt.dot(classMatrices[c]) )
    
print (PhiKY)
PhiKY = np.array(PhiKY)
print (PhiKY, type(PhiKY))
# print (Xt.shape, classMatrices[4].shape)
# S = Xt.dot(classMatrices[4])
# print (S.shape, S[:100])

[array([949, 262,   2, ...,   0,   0,   0], dtype=int64), array([375,  31,   1, ...,   0,   0,   0], dtype=int64), array([326,  16,   0, ...,   1,   0,   0], dtype=int64), array([464,  49,   0, ...,   0,   0,   0], dtype=int64), array([443, 111,   0, ...,   0,   1,   1], dtype=int64)]
[[949 262   2 ...   0   0   0]
 [375  31   1 ...   0   0   0]
 [326  16   0 ...   1   0   0]
 [464  49   0 ...   0   0   0]
 [443 111   0 ...   0   1   1]] <class 'numpy.ndarray'>


(4, 3) (3,)


array([ 1, -3, -1, -2], dtype=int64)

In [39]:
a = np.array([1,2,2,3])
b = (a == 2)
print (b)
np.sum(b)

[False  True  True False]


2