In [121]:
import numpy as np

def gen_docs ():
    docs = [
        ["This", "is", "doc", "number"],
        ["Hey", "it's","doc", "2"],
        ["boo", "document", "no"],
        ["hooa", "hoo"],
        ["bola", "bola", "bola"],
    ]
    
    for doc in docs:
        yield(np.array(doc))
        
def gen_ratings ():
    ratings = [
        "3",
        "4",
        "1",
        "5",
        "2"
    ]
        
    for r in ratings:
        yield(int(r))
        
for doc in gen_docs():
    print (doc)

['This' 'is' 'doc' 'number']
['Hey' "it's" 'doc' '2']
['boo' 'document' 'no']
['hooa' 'hoo']
['bola' 'bola' 'bola']


In [122]:
import numpy as np
docs = np.array([doc for doc in gen_docs()])
ratings = np.array([rating for rating in gen_ratings()])

dictionary = np.unique(np.concatenate(docs))
dictionary = { doc : idx for idx, doc in enumerate(dictionary)}
print (ratings, docs, dictionary)


[3 4 1 5 2] [array(['This', 'is', 'doc', 'number'], dtype='<U6')
 array(['Hey', "it's", 'doc', '2'], dtype='<U4')
 array(['boo', 'document', 'no'], dtype='<U8')
 array(['hooa', 'hoo'], dtype='<U4')
 array(['bola', 'bola', 'bola'], dtype='<U4')] {'2': 0, 'Hey': 1, 'This': 2, 'bola': 3, 'boo': 4, 'doc': 5, 'document': 6, 'hoo': 7, 'hooa': 8, 'is': 9, "it's": 10, 'no': 11, 'number': 12}


In [123]:
# Computing Phi's
Phi = [None] * 5
for r in range (0, 5):
    Phi[r] = np.sum(ratings == r+1) / len (ratings)
    Phi[r] = np.log(Phi[r])
    
print (Phi)

[-1.6094379124341003, -1.6094379124341003, -1.6094379124341003, -1.6094379124341003, -1.6094379124341003]


In [126]:
# Computing ThetaWK's
V = len(dictionary)
print (V)

ThetaNum = np.zeros((V, 5)) + 1
ThetaDeno = np.zeros((V, 5)) + V 

def computeFreq (doc, rating):
#     w = dictionary()
    k = rating - 1
    print ("yay", doc, rating)
    ThetaDeno[:, k] += len(doc)
    
    for word, idx in dictionary.items():
        f = np.sum(doc == word)
        ThetaNum[idx][k] += f
    
    return 0
    
# print (docs, ratings)
print (dictionary, '\n')
# vComputeFreq = np.vectorize(computeFreq, otypes=[int])
# vComputeFreq(docs, ratings)

for doc, rating in zip(gen_docs(), gen_ratings()):
    computeFreq (doc, rating)
    
Theta = np.log(ThetaNum / ThetaDeno)

np.set_printoptions(precision=2)
print (ThetaNum)
print (ThetaDeno)
print (Theta)



13
{'2': 0, 'Hey': 1, 'This': 2, 'bola': 3, 'boo': 4, 'doc': 5, 'document': 6, 'hoo': 7, 'hooa': 8, 'is': 9, "it's": 10, 'no': 11, 'number': 12} 

yay ['This' 'is' 'doc' 'number'] 3
yay ['Hey' "it's" 'doc' '2'] 4
yay ['boo' 'document' 'no'] 1
yay ['hooa' 'hoo'] 5
yay ['bola' 'bola' 'bola'] 2
[[1. 1. 1. 2. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 2. 1. 1.]
 [1. 4. 1. 1. 1.]
 [2. 1. 1. 1. 1.]
 [1. 1. 2. 2. 1.]
 [2. 1. 1. 1. 1.]
 [1. 1. 1. 1. 2.]
 [1. 1. 1. 1. 2.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [2. 1. 1. 1. 1.]
 [1. 1. 2. 1. 1.]]
[[16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]]
[[-2.77 -2.77 -2.83 -2.14 -2.71]
 [-2.77 -2.77 -2.83 -2.14 -2.71]
 [-2.77 -2.77 -2.14 -2.83 -2.71]
 [-2.77 -1.39 -2.83 -2.83 -2.71]
 [-2.08 -2.77 -2.83 -2.83 -2.71]
 [-2.77

In [140]:
# Predictions
def predictClass (doc):
    probs = np.zeros(5)
    for k in range(0, 5):
        probs[k] += Phi[k];
        for word in doc:
            w = dictionary[word]
            probs[k] += Theta[w][k]
    print (probs)
    return np.argmax(probs) + 1


for doc in docs:
    prediction = predictClass (doc)
    print (prediction)

[-12.7  -12.7  -10.17 -12.25 -12.44]
3
[-12.7  -12.7  -12.25 -10.17 -12.44]
4
[ -7.85  -9.93 -10.11 -10.11  -9.73]
1
[-7.15 -7.15 -7.28 -7.28 -5.64]
5
[ -9.93  -5.77 -10.11 -10.11  -9.73]
2
