In [159]:
import numpy as np

def gen_docs ():
    docs = [
        ["This", "is", "doc", "number"],
        ["Hey", "it's","doc", "2"],
        ["boo", "document", "no"],
        ["hooa", "hoo"],
        ["bola", "bola", "bola"],
    ]
    
    for doc in docs:
        yield(np.array(doc))
        
def gen_ratings ():
    ratings = [
        "3",
        "4",
        "1",
        "5",
        "2"
    ]
        
    for r in ratings:
        yield(int(r))
        
for doc in gen_docs():
    print (doc)

['This' 'is' 'doc' 'number']
['Hey' "it's" 'doc' '2']
['boo' 'document' 'no']
['hooa' 'hoo']
['bola' 'bola' 'bola']


In [160]:
import numpy as np
docs = np.array([doc for doc in gen_docs()])
ratings = np.array([rating for rating in gen_ratings()])

# dictionary = np.unique(np.concatenate(docs))
# dictionary = { doc : idx for idx, doc in enumerate(dictionary)}
# print (ratings, docs, dictionary)

dictionary = {}
for doc in gen_docs():
    for word in doc:
        dictionary[word] = 0
        
dictionary = { word : idx for idx, word in enumerate(dictionary)}

print (dictionary)


{'This': 0, 'is': 1, 'doc': 2, 'number': 3, 'Hey': 4, "it's": 5, '2': 6, 'boo': 7, 'document': 8, 'no': 9, 'hooa': 10, 'hoo': 11, 'bola': 12}


In [165]:
# Computing Phi's
Phi = np.zeros(5)

totalRatings = 0
for rating in gen_ratings():
    totalRatings += 1
    Phi[rating - 1] += 1

Phi /= totalRatings
Phi = np.log(Phi)
# for r in range (0, 5):
#     Phi[r] = np.sum(ratings == r+1) / len (ratings)
#     Phi[r] = np.log(Phi[r])
    
print (Phi)

[-1.61 -1.61 -1.61 -1.61 -1.61]


In [162]:
# Computing ThetaWK's
V = len(dictionary)
print (V)

ThetaNum = np.zeros((V, 5)) + 1
ThetaDeno = np.zeros((V, 5)) + V 

def computeFreq (doc, rating):
#     w = dictionary()
    k = rating - 1
    print ("yay", doc, rating)
    ThetaDeno[:, k] += len(doc)
    
    for word, idx in dictionary.items():
        f = np.sum(doc == word)
        ThetaNum[idx][k] += f
    
    return 0
    
# print (docs, ratings)
print (dictionary, '\n')
# vComputeFreq = np.vectorize(computeFreq, otypes=[int])
# vComputeFreq(docs, ratings)

for doc, rating in zip(gen_docs(), gen_ratings()):
    computeFreq (doc, rating)
    
Theta = np.log(ThetaNum / ThetaDeno)

np.set_printoptions(precision=2)
print (ThetaNum)
print (ThetaDeno)
print (Theta)



13
{'This': 0, 'is': 1, 'doc': 2, 'number': 3, 'Hey': 4, "it's": 5, '2': 6, 'boo': 7, 'document': 8, 'no': 9, 'hooa': 10, 'hoo': 11, 'bola': 12} 

yay ['This' 'is' 'doc' 'number'] 3
yay ['Hey' "it's" 'doc' '2'] 4
yay ['boo' 'document' 'no'] 1
yay ['hooa' 'hoo'] 5
yay ['bola' 'bola' 'bola'] 2
[[1. 1. 2. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 2. 2. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 2. 1.]
 [2. 1. 1. 1. 1.]
 [2. 1. 1. 1. 1.]
 [2. 1. 1. 1. 1.]
 [1. 1. 1. 1. 2.]
 [1. 1. 1. 1. 2.]
 [1. 4. 1. 1. 1.]]
[[16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]
 [16. 16. 17. 17. 15.]]
[[-2.77 -2.77 -2.14 -2.83 -2.71]
 [-2.77 -2.77 -2.14 -2.83 -2.71]
 [-2.77 -2.77 -2.14 -2.14 -2.71]
 [-2.77 -2.77 -2.14 -2.83 -2.71]
 [-2.77 -2.77 -2.83 -2.14 -2.71]
 [-2.77

In [163]:
# Predictions
def predictClass (doc):
    probs = np.zeros(5)
    for k in range(0, 5):
        probs[k] += Phi[k];
        for word in doc:
            w = dictionary[word]
            probs[k] += Theta[w][k]
    return np.argmax(probs) + 1

correctPredictions = 0
totalPredictions = 0
for doc, rating in zip(gen_docs(), gen_ratings()):
    prediction = predictClass (doc)
    totalPredictions += 1
    if (prediction == rating):
        correctPredictions += 1
    
print ("Accuracy: %.2f%%" % (correctPredictions * 100 / totalPredictions))

Accuracy: 100.00%
