In [7]:
# from python.svm import *
from libsvm.python.svmutil import *

In [8]:
y, x = [1,-1], [[1,0,1], [-1,0,-1]]
prob  = svm_problem(y, x)
param = svm_parameter('-t 0 -c 4 -b 1')
m = svm_train(prob, param)

In [7]:
import numpy as np

X = [[1,2,3], [4,5,6]]

XtX = np.multiply(X, X)
print (XtX)
XtX = np.sum(XtX, axis=1).reshape(2,1)
print (XtX, X)

print (X + XtX)

[[ 1  4  9]
 [16 25 36]]
[[14]
 [77]] [[1, 2, 3], [4, 5, 6]]
[[15 16 17]
 [81 82 83]]


In [14]:
y = np.matrix([1,2]).T
print (y)
np.repeat(y, 2, axis=1)

[[1]
 [2]]


matrix([[1, 1],
        [2, 2]])

In [25]:
def gaussianB (X):
    X = np.matrix(X)
    m, n = X.shape
    XtX = np.multiply(X, X)
    XtX = np.sum(XtX, axis=1).reshape(m,1)
    XtX = np.repeat(XtX, m, axis=1)
    print (XtX)
    print ((X*X.T).shape)
    return XtX + XtX.T - 2*X*X.T

def gaussianM (X):
    XB = gaussianB(X)
    gamma = 0.05
    return np.exp ( -gamma * XB)
    
X = np.array([[1,2,3], [4,5,6], [7,8,9], [0,3,4]])
G = gaussianB(X)
M = gaussianM(X)
print (G)
print (M)

[[ 14  14  14  14]
 [ 77  77  77  77]
 [194 194 194 194]
 [ 25  25  25  25]]
(4, 4)
[[ 14  14  14  14]
 [ 77  77  77  77]
 [194 194 194 194]
 [ 25  25  25  25]]
(4, 4)
[[  0  27 108   3]
 [ 27   0  27  24]
 [108  27   0  99]
 [  3  24  99   0]]
[[1.         0.25924026 0.00451658 0.86070798]
 [0.25924026 1.         0.25924026 0.30119421]
 [0.00451658 0.25924026 1.         0.00708341]
 [0.86070798 0.30119421 0.00708341 1.        ]]


In [29]:
print (X)
print (X - [1,2,3])
print (np.sum(X, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 3 4]]
[[ 0  0  0]
 [ 3  3  3]
 [ 6  6  6]
 [-1  1  1]]
[ 6 15 24  7]


In [31]:
def test(x):
    return x*10

a = np.array([1,2,3])
test(a)

array([10, 20, 30])